name: Test On Review

description: Test the on review workflow

runs:
  using: 'composite'
  steps:
    - name: Check Required Reviews
      uses: actions/github-script@v7
      with:
        script: |
          // Check if there are any reviews on the pull request
          const reviews = await github.rest.pulls.listReviews({
            owner: context.repo.owner,
            repo: context.repo.repo,
            pull_number: context.payload.pull_request.number,
          });
          if (reviews.data.length === 0) {
            throw new Error('No reviews found on this pull request');
          }
          // Check that the most recent review is an approval review
          const mostRecentReview = reviews.data.sort((a, b) => new Date(b.submitted_at) - new Date(a.submitted_at))[0];
          if (mostRecentReview.state !== 'APPROVED') {
            throw new Error('The most recent review on this pull request is not an approval review');
          }