name: Test On Review

description: Test the on review workflow

runs:
  using: 'composite'
  steps:
    - name: Check Required Reviews
      uses: actions/github-script@v7
      with:
        script: |
          # Check if there are any reviews on the pull request
          const reviews = await github.rest.pulls.listReviews({
            owner: context.repo.owner,
            repo: context.repo.repo,
            pull_number: context.payload.pull_request.number,
          });
          if (reviews.data.length === 0) {
            exit(1);
          }
          # Check that there is one approval review
          const approvalReview = reviews.data.find(review => review.state === 'APPROVED');
          if (!approvalReview) {
            exit(1);
          }
          exit(0);